### ISSUE TITLE
Moving cropper results in cut off images

### ISSUE THREAD

**Issue by mergesort** [lucasecf/LECropPictureViewController#9]
I'm using the control, and the second I move it off center, it crops out a part of the image. An example below. Any thoughts? It's just out of the box working like this. (iOS 9/simulator)

![cropper](https://cloud.githubusercontent.com/assets/716513/10553607/399918f8-742a-11e5-905f-8640acad1362.png)

![cropped](https://cloud.githubusercontent.com/assets/716513/10553608/3b8ea7a4-742a-11e5-8748-996f1c983c43.png)

**Comment by lucasecf** [comment]
Hello @mergesort , 

Can you provide full steps to reproduce the problem? Or even a small project hosted somewhere?

**Comment by lucasecf** [comment]
Closing this for lack of ways to reproduce. Please, if anyone have the same problem, don't hesitate to post and open the issue again, with more informations of how to reproduce it.
